name: SelfShooting
version: "1.2"
author: 7isenko
main: io.github._7isenko.selfshooting.SelfShooting
commands:
  bows:
    description: Turns on/off the plugin
    usage: /bows all or /bows players
    permission: selfshooting.command
permissions:
  selfshooting.command:
    description: Permission to turn on/off the self shooting mode
    default: op